spring.application.name=CRAS-Phase2

spring.datasource.url=jdbc:mysql://localhost:3306/cras
spring.datasource.username=root
spring.datasource.password=krishna1708@

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8090
